[extension]
name = "pg_ivm"
version = "1.8.0+partitioning"
repository = "https://github.com/sraoss/pg_ivm"
license = "PostgreSQL"
description = "IVM (Incremental View Maintenance) implementation as a PostgreSQL extension"
homepage = "https://www.sraoss.co.jp/index_en/"
documentation = "https://github.com/sraoss/pg_ivm"
categories = ["change_data_capture"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "15"
platform = "linux/amd64"
